name: MAVSDK-Swift-Example
options:
  deploymentTarget:
    iOS: "11.2"
  bundleIdPrefix: io.mavlink.mavsdk
settings:
  ENABLE_BITCODE: NO
targets:
  MAVSDK_Swift_Example:
    type: application
    platform: iOS
    info:
      path: Sources/MAVSDK-Swift-Example/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortraitUpsideDown]
    settings:
      configs:
        debug:
          SWIFT_OBJC_BRIDGING_HEADER: "Sources/MAVSDK-Swift-Example/MAVSDK-Swift-Example-Bridging-Header.h"
        release:
          SWIFT_OBJC_BRIDGING_HEADER: "Sources/MAVSDK-Swift-Example/MAVSDK-Swift-Example-Bridging-Header.h"
    sources: [Sources/MAVSDK-Swift-Example]
    dependencies:
      - carthage: mavsdk_server
      - carthage: BoringSSL
      - carthage: CgRPC
      - carthage: MAVSDK_Swift
      - carthage: MobileVLCKit
        embed: false
      - carthage: RxBlocking
      - carthage: RxSwift
      - carthage: SwiftGRPC
      - carthage: SwiftProtobuf
      - sdk: AVFoundation.framework
      - sdk: AudioToolbox.framework
      - sdk: CoreMedia.framework
      - sdk: libbz2.tbd
      - sdk: libiconv.tbd
      - sdk: VideoToolbox.framework
    directlyEmbedCarthageDependencies: true
